### ISSUE TITLE
Add ports

### ISSUE THREAD

**Issue by reinethernal** [EvilFreelancer/docker-routeros#1]
Is there any way to add ethernet ports to ROS in this container?

**Comment by EvilFreelancer** [comment]
Hello!

Yep, you may use docker-compose config, for example:
```yml
version: "3"

services:

  routeros-6-42:
    image: evilfreelancer/docker-routeros:6.42.12
    restart: unless-stopped
    ports:
      - "12222:22"
      - "12223:23"
      - "18728:8728"
      - "18729:8729"
      ....list of additional ports....
```
Or pure docker way, and with -p prive to docker list of ports
```
docker run -d -p 2222:22 -p 8728:8728 -p 8729:8729 -p 5900:5900 -ti evilfreelancer/docker-routeros
```
