### ISSUE TITLE
How to activate KVM

### ISSUE THREAD

**Issue by maxgamingir** [EvilFreelancer/docker-routeros#26]
the cpu usage is too high
how to activate -enable-kvm on QEMU and config docker to access to KVM module?

**Comment by EvilFreelancer** [comment]
Hi! In Dockerfile you may find an [ENTRYPOINT](https://github.com/EvilFreelancer/docker-routeros/blob/master/Dockerfile#L32) directive:

```dockerfile
ENTRYPOINT ["/routeros/entrypoint.sh"]
```

Content of entrypoint.sh is [here](https://github.com/EvilFreelancer/docker-routeros/blob/master/scripts/entrypoint.sh).

You can write your own entrypoin.sh script and mount it with help of docker volumes, like that:

```yml
version: "3"
services:
  routeros:
    image: evilfreelancer/docker-routeros
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm
    volumes:
      - ./entrypoin.custom.sh:/routeros/entrypoint.sh
```
