### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by dmytroshokha** [EvilFreelancer/docker-routeros#4]
Hi, i made docker run -d -p 2222:22 -p 8728:8728 -p 8729:8729 -p 5900:5900 -ti ros and can connect via ssh to localhost but i can not connect by winbox.

**Comment by EvilFreelancer** [comment]
Hello! For enabling winbox you need first to go to ROS via ssh of via web and turn on winbox service via ROS system settings.

**Comment by dmytroshokha** [comment]
Enabled  winbox service  8291 192.168.88.1/32 but still can not connect via winbox. Should i firstly create new login\pass for connection?

**Comment by EvilFreelancer** [comment]
Of course, without it ssh and winbox won't work

**Comment by dmytroshokha** [comment]
Hmm, i changed default login\pass but still can not connect using winbox. May be could you write the steps, what should i do to connect via winbox after docker run?

**Comment by EvilFreelancer** [comment]
Btw, did you specified this port in settings of docker compose?

```yml
version: "3"

services:

  routeros:
    image: evilfreelancer/docker-routeros:latest
    restart: unless-stopped
    ports:
      - "2222:22"
      - "2223:23"
      - "7777:80"
      - "8291:8291"
      - "8728:8728"
      - "8729:8729"
```
