### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by hzwjm** [EvilFreelancer/docker-routeros#5]
Hello, failed to start using least image.

# docker logs routeros
Failed to send flush request: Operation not permitted
RTNETLINK answers: Operation not permitted
Error: argument "qemubr0" is wrong: Device does not exist

RTNETLINK answers: Operation not permitted
Cannot find device "qemubr0"
udhcpd: started, v1.31.1
udhcpd: max_leases=235 is too big, setting to 1
udhcpd: can't open '/var/lib/udhcpd/udhcpd.leases': No such file or directory
udhcpd: ioctl 0x8933 failed: No such device
qemu-system-x86_64: could not open /dev/net/tun: No such file or directory

**Comment by EvilFreelancer** [comment]
Hello! Seems you not pushed /dev/net/tun into your docker container and not enabled NET_ADMIN, try someting like this:
```yml
version: "3"

services:

  routeros-6-44:
    image: evilfreelancer/docker-routeros:6.46.5
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "22222:22"
      - "22223:23"
      - "28728:8728"
      - "28729:8729"
```
