### ISSUE TITLE
docker container not running after created

### ISSUE THREAD

**Issue by aliraee** [EvilFreelancer/docker-routeros#51]
hello,
I used your docker container and getting this error in logs:
RTNETLINK answers: Operation not permitted
Cannot find device "qemubr1"
KVM not available, running in emulation mode. This will be slow.
udhcpd: started, v1.36.1
udhcpd: max_leases=235 is too big, setting to 1
udhcpd: can't open '/var/lib/udhcpd/udhcpd.leases': No such file or directory
udhcpd: ioctl 0x8933 failed: No such device
qemu-system-x86_64: -nic tap,id=qemu1,mac=54:05:AB:CD:12:31,script=/routeros/qemu-ifup,downscript=/routeros/qemu-ifdown: could not open /dev/net/tun: No such file or directory

how to fix this issue?
thanks.

**Comment by EvilFreelancer** [comment]
Hi!

> KVM not available

Mean KVM disabled in BIOS

**Comment by juliardi** [comment]
Got the same problem here. And I have checked BIOS and there is no KVM options there. If you mean the virtualization option, then it is already enabled. Do I need to install some packages in my host OS? I am using EndeavourOS.

**Comment by juliardi** [comment]
Sorry, I found the problem. Turns out I have not installed `qemu` in my host OS. This is what I did :
1. Install `qemu` 
```bash
yay -S extra/qemu-base
```
2. Create `docker-compose.yml` file 
```yml
routeros-latest:
    image: evilfreelancer/docker-routeros:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm
    ports:
      - "22222:22"
      - "22223:23"
      - "7777:80"
      - "8728:8728"
      - "8729:8729"
      - "28728:8728"
      - "28729:8729"
```
3. Run docker-compose
```bash
docker-compose up
```
4. Try to access localhost:7777 from browser
