### ISSUE TITLE
How to localize the data?

### ISSUE THREAD

**Issue by jonnyman12345** [EvilFreelancer/docker-routeros#63]
How to localize the data?

**Comment by EvilFreelancer** [comment]
Hi! RouterOS is not supporting other locales but only english.

**Comment by jonnyman12345** [comment]
i ,mean How to save the data? such user data

**Comment by ssamu-id** [comment]
how to make the routerOS not lose it's config after the container restart?

**Comment by EvilFreelancer** [comment]
Example of docker-compose.yaml for reproducing:

```yaml
services:

  routeros:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ROUTEROS_VERSION=7.20.8
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm
    ports:
      - "8080:80"
      - "2222:22"
      - "2223:23"
      - "8728:8728"
      - "8729:8729"
    volumes:
      - ./routeros_data:/data
    networks:
      - default
      - routeros_net

networks:
  routeros_net:
    driver: bridge
```
