### ISSUE TITLE
Initial configuration

### ISSUE THREAD

**Issue by StefanYohansson** [EvilFreelancer/docker-routeros#7]
Hi, thank you for the repo, it is a really nice idea.

I have one doubt regarding the RouterOS initial configuration, I have one docker-compose and I want to run some command or something in order to configure it (configure ppoe and radius).
do you have any way or idea of how to run a script to initially configure the Mikrotik?

```
isprouter:
                image: evilfreelancer/docker-routeros
                restart: unless-stopped
                cap_add:
                        - NET_ADMIN
                devices:
                        - /dev/net/tun
                ports:
                        - "2222:22"
                        - "2223:23"
                        - "8728:8728"
                        - "8729:8729"
                        - "8291:8291"
                networks:
                        static-network:
                                ipv4_address: 172.20.128.5
```
